// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {json} from '../models';

export function CreateCollection(arg1:string,arg2:string):Promise<main.Collection>;

export function CreateNote(arg1:string,arg2:string):Promise<main.Note>;

export function DeleteCollection(arg1:string):Promise<void>;

export function DeleteNote(arg1:string):Promise<void>;

export function GetCollections(arg1:string):Promise<Array<main.Collection>>;

export function GetNotes(arg1:string):Promise<Array<main.Note>>;

export function GetVault():Promise<main.Vault>;

export function Greet(arg1:string):Promise<string>;

export function ImportVault():Promise<main.Vault>;

export function LoadVaultPath():Promise<string>;

export function ReadNote(arg1:string):Promise<main.Note>;

export function RenameCollection(arg1:string,arg2:string):Promise<void>;

export function RenameNote(arg1:string,arg2:string):Promise<main.Note>;

export function SaveNote(arg1:string,arg2:string,arg3:json.RawMessage):Promise<void>;

export function SaveVaultPath(arg1:string):Promise<void>;

export function SearchNotes(arg1:string,arg2:string):Promise<Array<main.Note>>;
