// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateCollection(arg1, arg2) {
  return window['go']['main']['App']['CreateCollection'](arg1, arg2);
}

export function CreateNote(arg1, arg2) {
  return window['go']['main']['App']['CreateNote'](arg1, arg2);
}

export function DeleteCollection(arg1) {
  return window['go']['main']['App']['DeleteCollection'](arg1);
}

export function DeleteNote(arg1) {
  return window['go']['main']['App']['DeleteNote'](arg1);
}

export function GetCollections(arg1) {
  return window['go']['main']['App']['GetCollections'](arg1);
}

export function GetNotes(arg1) {
  return window['go']['main']['App']['GetNotes'](arg1);
}

export function GetVault() {
  return window['go']['main']['App']['GetVault']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ImportVault() {
  return window['go']['main']['App']['ImportVault']();
}

export function LoadVaultPath() {
  return window['go']['main']['App']['LoadVaultPath']();
}

export function ReadNote(arg1) {
  return window['go']['main']['App']['ReadNote'](arg1);
}

export function RenameCollection(arg1, arg2) {
  return window['go']['main']['App']['RenameCollection'](arg1, arg2);
}

export function RenameNote(arg1, arg2) {
  return window['go']['main']['App']['RenameNote'](arg1, arg2);
}

export function SaveNote(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveNote'](arg1, arg2, arg3);
}

export function SaveVaultPath(arg1) {
  return window['go']['main']['App']['SaveVaultPath'](arg1);
}

export function SearchNotes(arg1, arg2) {
  return window['go']['main']['App']['SearchNotes'](arg1, arg2);
}
